import type { ContractArtifact } from '@cashlang/shared';

export function generateDeploymentScript(artifact: ContractArtifact, network: 'mainnet' | 'testnet' = 'testnet'): string {
  const params = artifact.constructorInputs.map(input => {
    switch (input.type) {
      case 'pubkey':
        return `  const ${input.name} = new SignatureTemplate(wallet);`;
      case 'int':
        return `  const ${input.name} = 1000; // Replace with your value`;
      case 'bytes':
        return `  const ${input.name} = hexToBin('deadbeef'); // Replace with your bytes`;
      default:
        return `  const ${input.name} = /* your ${input.type} value */;`;
    }
  }).join('\n');

  const paramNames = artifact.constructorInputs.map(i => i.name).join(', ');

  return `// Deployment script for ${artifact.contractName}
// Generated by CashLang v${artifact.compiler.version}

import { Contract, SignatureTemplate, ElectrumNetworkProvider } from 'cashscript';
import { hexToBin } from '@bitauth/libauth';
import artifact from './${artifact.contractName}.json' assert { type: 'json' };

async function deploy() {
  // 1. Set up network provider
  const provider = new ElectrumNetworkProvider('${network}');
  
  // 2. Set up wallet (replace with your wallet)
  const wallet = /* your wallet setup */;
  
  // 3. Set constructor parameters
${params}
  
  // 4. Create contract instance
  const contract = new Contract(artifact, [${paramNames}], { provider });
  
  // 5. Get contract address
  console.log('Contract address:', contract.address);
  console.log('Contract balance:', await contract.getBalance());
  
  // 6. Fund the contract (optional)
  // Send BCH to the contract address to fund it
  
  return contract;
}

// Run deployment
deploy()
  .then(contract => {
    console.log('✅ Contract deployed successfully!');
    console.log('Address:', contract.address);
  })
  .catch(error => {
    console.error('❌ Deployment failed:', error);
    process.exit(1);
  });
`;
}

export function generateTestScript(artifact: ContractArtifact): string {
  const firstFunction = artifact.abi[0];
  if (!firstFunction) {
    return '// No functions to test';
  }

  const params = firstFunction.inputs.map(input => {
    switch (input.type) {
      case 'sig':
        return `    ${input.name}: new SignatureTemplate(wallet)`;
      case 'int':
        return `    ${input.name}: 100`;
      case 'bytes':
        return `    ${input.name}: hexToBin('deadbeef')`;
      default:
        return `    ${input.name}: /* your ${input.type} value */`;
    }
  }).join(',\n');

  return `// Test script for ${artifact.contractName}
// Generated by CashLang

import { Contract, SignatureTemplate, ElectrumNetworkProvider } from 'cashscript';
import { hexToBin } from '@bitauth/libauth';
import artifact from './${artifact.contractName}.json' assert { type: 'json' };

async function test() {
  // Set up provider and wallet
  const provider = new ElectrumNetworkProvider('testnet');
  const wallet = /* your wallet */;
  
  // Create contract (replace with your constructor args)
  const contract = new Contract(artifact, [/* constructor args */], { provider });
  
  // Call ${firstFunction.name} function
  const tx = await contract.functions
    .${firstFunction.name}(
${params}
    )
    .to(contract.address, 1000n) // Send to contract
    .send();
  
  console.log('✅ Transaction sent:', tx.txid);
  return tx;
}

test().catch(console.error);
`;
}

export function generateReadme(artifact: ContractArtifact): string {
  return `# ${artifact.contractName}

Smart contract generated by CashLang.

## Contract Details

- **Name:** ${artifact.contractName}
- **Compiler:** ${artifact.compiler.name} v${artifact.compiler.version}
- **Bytecode Size:** ${artifact.bytecode.length / 2} bytes
- **Functions:** ${artifact.abi.length}

## Constructor Parameters

${artifact.constructorInputs.map(input => `- \`${input.name}\` (${input.type})`).join('\n')}

## Functions

${artifact.abi.map(fn => {
  const params = fn.inputs.map(i => `${i.name}: ${i.type}`).join(', ');
  return `### ${fn.name}(${params})

${fn.inputs.length > 0 ? 'Parameters:\n' + fn.inputs.map(i => `- \`${i.name}\` (${i.type})`).join('\n') : 'No parameters'}
`;
}).join('\n')}

## Deployment

1. Install dependencies:
\`\`\`bash
npm install cashscript @bitauth/libauth
\`\`\`

2. Run deployment script:
\`\`\`bash
node deploy.js
\`\`\`

3. Test the contract:
\`\`\`bash
node test.js
\`\`\`

## Generated Files

- \`${artifact.contractName}.json\` - Contract artifact
- \`${artifact.contractName}.cash\` - CashScript source
- \`deploy.js\` - Deployment script
- \`test.js\` - Test script
- \`README.md\` - This file

## Learn More

- [CashScript Documentation](https://cashscript.org)
- [CashLang Documentation](https://cashlang.dev)
- [Bitcoin Cash](https://bitcoincash.org)
`;
}
